spring.application.name=ai-resume-builder

#Mongodb Connection
spring.data.mongodb.uri=mongodb+srv://amanuser:ai%4012@airesume.cwpervm.mongodb.net/ai-resume-db?retryWrites=true&w=majority&appName=AIRESUME

jwt.secret=a_very_long_and_secure_secret_key_that_no_one_can_guess_123456789